version: 0.2

env:
    variables:
        S3_BUCKET: "{{s3_bucket_url}}"

phases:
  pre_build:
    commands:
        - echo Installing source NPM dependencies...
        - cd client/
        - npm install
        - echo ----------------------- listando arquivos -----------------------
        - ls -ll
        - echo ----------------------- PATH DOS ARQUIVOS -----------------------
        - pwd
        
  build:
    commands:
        - echo ----------------------- Build started -----------------------
        - npm run build
        
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/client*'
    discard-paths: yes